### ISSUE TITLE
почему не panic/fatal?

### ISSUE THREAD

**Issue by Kirill-Shkodkin** [grumpycatyo-collab/turbo-pancake#1]
https://github.com/grumpycatyo-collab/turbo-pancake/blob/afcf0c8072a20f3659d2b4ec92064488c7b83bc2/app/main.go#L22

**Comment by grumpycatyo-collab** [comment]
Я мог бы использовать панику, и заполучить traceback моей ошибки. Но на данный момент я посчитал что лучше оставить os.Exit(1), который просто показывает мне ошибку, потому что на данный момент мой код не такой обширный и мне попросту не нужна паника.Как вы считаете?
