### ISSUE TITLE
Использование транзакции

### ISSUE THREAD

**Issue by Kirill-Shkodkin** [grumpycatyo-collab/turbo-pancake#2]
1. Зачем тут транзакция?
2. Допустим нужна, где её использование дальше? она просто объявлена, у неё нет коммита. Квери ниже выполняются без транзакции

https://github.com/grumpycatyo-collab/turbo-pancake/blob/afcf0c8072a20f3659d2b4ec92064488c7b83bc2/business/data/dbschema/dbschema.go#L58C2-L58C4

**Comment by grumpycatyo-collab** [comment]
Я использовал ( пытался использовать но забыл слинковать tx) транзакции из-за обеспечения целостности данных в бд. Всегда если что-то не то произойдёт, есть deffer tx.Rollback().  Плюс, транзакция будучи множество query должна всегда убеждаться что каждая из её query  выполнилась  и только потом их коммитить.
